"""add_google_id_to_user

Revision ID: 269e2738d94b
Revises: 7044205f6d33
Create Date: 2026-02-22 21:30:25.843021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269e2738d94b'
down_revision: Union[str, Sequence[str], None] = '7044205f6d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False)
        batch_op.drop_column('google_id')
    # ### end Alembic commands ###
