"""add realized_pnl to transactions

Revision ID: 6fee44d3d0de
Revises: d0c6e53606f8
Create Date: 2026-02-23 19:56:54.909603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fee44d3d0de'
down_revision: Union[str, Sequence[str], None] = 'd0c6e53606f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False, comment='已實現損益 (僅 SELL/DIVIDEND 類型有值)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'realized_pnl')
    # ### end Alembic commands ###
