"""initial_schema

Revision ID: d0c6e53606f8
Revises: 
Create Date: 2026-02-22 23:13:25.838243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c6e53606f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='標的代碼'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='標的名稱'),
    sa.Column('total_quantity', sa.Numeric(precision=18, scale=8), nullable=False, comment='總持有數量'),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=8), nullable=False, comment='加權平均成本'),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_portfolio_symbol')
    )
    op.create_index(op.f('ix_current_positions_portfolio_id'), 'current_positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_current_positions_symbol'), 'current_positions', ['symbol'], unique=False)
    op.create_table('historical_net_worth',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='快照日期'),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=4), nullable=False, comment='總資產價值'),
    sa.Column('total_liabilities', sa.Numeric(precision=18, scale=4), nullable=False, comment='總負債價值'),
    sa.Column('net_worth', sa.Numeric(precision=18, scale=4), nullable=False, comment='淨值 = 總資產 - 總負債'),
    sa.Column('breakdown', sa.JSON(), nullable=True, comment='各類別資產明細 JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uq_portfolio_date')
    )
    op.create_index(op.f('ix_historical_net_worth_portfolio_id'), 'historical_net_worth', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_historical_net_worth_snapshot_date'), 'historical_net_worth', ['snapshot_date'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='標的代碼，如 2330.TW, AAPL, BTC'),
    sa.Column('asset_name', sa.String(length=100), nullable=True, comment='標的名稱，如 台積電、Apple'),
    sa.Column('tx_type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'DEPOSIT', 'WITHDRAW', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False, comment='交易數量（加密貨幣支援小數）'),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=8), nullable=False, comment='單位價格'),
    sa.Column('fee', sa.Numeric(precision=18, scale=4), nullable=False, comment='手續費'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='交易幣別'),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False, comment='交易執行時間'),
    sa.Column('note', sa.String(length=500), nullable=True, comment='備註'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_portfolio_id'), 'transactions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_transactions_symbol'), 'transactions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_symbol'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_portfolio_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_historical_net_worth_snapshot_date'), table_name='historical_net_worth')
    op.drop_index(op.f('ix_historical_net_worth_portfolio_id'), table_name='historical_net_worth')
    op.drop_table('historical_net_worth')
    op.drop_index(op.f('ix_current_positions_symbol'), table_name='current_positions')
    op.drop_index(op.f('ix_current_positions_portfolio_id'), table_name='current_positions')
    op.drop_table('current_positions')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('asset_categories')
    # ### end Alembic commands ###
